### ISSUE TITLE
Errores al ejecutar las pruebas de Caja Negra

### ISSUE THREAD

**Issue by DrXoo** [EGC-AgoraResultsTest/agora-results-tests#6]
Al ejecutar las pruebas con pyb tras la primera prueba de integración con el grupo que modifica Agora-Results nos encontramos con que ninguna de las pruebas de caja negra funcionan, dando este error:

```
[ERROR] Test has error: 1To4_tests.tests.test_04
Traceback (most recent call last):
  File "/home/egc-dev/Escritorio/EGC/agora-results-tests/src/unittest/python/1To4_tests.py", line 60, in test_04
    jsonObject = utils.getJsonObjectFromResults()
  File "/home/egc-dev/Escritorio/EGC/agora-results-tests/src/main/python/utils.py", line 19, in getJsonObjectFromResults
    return json.loads(data)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by DrXoo** [comment]
El causante del error ha sido que Agora-Results se ha modificado para que el archivo de configuración ahora sea obligatorio. Se ha modificado el código para arreglar este fallo.
